export const DISPLAY_VOCABULARY_FOLDER_CREATION = 'DISPLAY_VOCABULARY_FOLDER_CREATION';
export const CREATE_VOCABULARY_FOLDER = 'CREATE_VOCABULARY_FOLDER';
export const VOCABULARY_FOLDER_CREATED = 'VOCABULARY_FOLDER_CREATED';
export const VOCABULARY_FOLDERS_RETRIEVED = 'VOCABULARY_FOLDERS_RETRIEVED';